name: ci

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'adopt'
        cache: maven
        
    - name: Build with Maven
      working-directory: ./backend/pdf_repository
      run: mvn clean package -DskipTests
      
    - name: Docker Build Backend
      working-directory: ./backend/pdf_repository
      run: docker build -t brgambim/pdf-repository-backend .
      
    - name: Docker Push Backend
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/pdf-repository-backend:latest ${{ secrets.DOCKER_USERNAME }}/pdf-repository-backend:${{ github.run_id }}
        docker run ${{ secrets.DOCKER_USERNAME }}/pdf-repository-backend
        docker run ${{ secrets.DOCKER_USERNAME }}/pdf-repository-backend:${{ github.run_id }}
