name: ci

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Set up MySQL Database
      run: docker run -d -e MYSQL_ROOT_PASSWORD=${{ secrets.ACTION_DB_PASSWORD }} -e MYSQL_DATABASE=pdf_repository_application -p 3306:3306 mysql:8.0.33

    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'adopt'
        cache: maven
        
    - name: Build with Maven
      working-directory: ./backend/pdf_repository
      env:
        SPRING.DATASOURCE.URL: jdbc:mysql://localhost:3306/pdf_repository_application
        SPRING.DATASOURCE.USERNAME: root
        SPRING.DATASOURCE.PASSWORD: ${{ secrets.ACTION_DB_PASSWORD }}
      run: mvn clean package
      
    - name: Docker Build Backend
      working-directory: ./backend/pdf_repository
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/pdf-repository-backend .
      
    - name: Docker Push Backend
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/pdf-repository-backend:latest ${{ secrets.DOCKER_USERNAME }}/pdf-repository-backend:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/pdf-repository-backend
        docker push ${{ secrets.DOCKER_USERNAME }}/pdf-repository-backend:${{ github.run_id }}
        
    - name: Docker Build Frontend
      working-directory: ./frontend/pdf_repository
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/pdf-repository-frontend .
      
    - name: Docker Push Frontend
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/pdf-repository-frontend:latest ${{ secrets.DOCKER_USERNAME }}/pdf-repository-frontend:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/pdf-repository-frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/pdf-repository-frontend:${{ github.run_id }}
